### ISSUE TITLE
建议添加下载速度悬浮窗以及后台运行功能

### ISSUE THREAD

**Issue by marcosteam** [mayswind/AriaNg-Native#1]
对于Aria2的重度使用者，Ariang的本地端每次关闭后并不会后台运行，并且下载时没有类似于迅雷的悬浮窗，每次想查看下载进度都只能频繁地打开程序，有点闹心，希望作者增加这个功能

**Comment by mayswind** [comment]
AriaNg Native是基于html+js，通过Electron构建的应用程序，目前由于系统限制实现不了悬浮窗。后台以及悬浮窗只能建议您使用其他的纯本地应用。
