### ISSUE TITLE
[Q&A] when I expect the version 1.2.5?

### ISSUE THREAD

**Issue by bachig26** [mayswind/AriaNg-Native#100]
[1.2.5](https://github.com/mayswind/AriaNg/releases/tag/1.2.5)

and other possible changes to desktop module?

**Comment by mayswind** [comment]
Don't worry, the new version of AriaNg Native will be released soon. But the next version is 1.3.0 instead of 1.2.5.

**Comment by mayswind** [comment]
The new release has been published.
