### ISSUE TITLE
[Q&A] Aria2 can't connect, help!

### ISSUE THREAD

**Issue by bachig26** [mayswind/AriaNg-Native#101]
the Aria2 Status stays `Disconnected`. I don't know how to fix it. the localhost doesn't work/start.

when I used the [AriaNg](https://github.com/mayswind/AriaNg), it worked straight out of box.

can you help me how to solve this?

**Comment by mayswind** [comment]
you can export settings from AriaNg, and import this to AriaNg Native

**Comment by bachig26** [comment]
> you can export settings from AriaNg, and import this to AriaNg Native

okay, i'll try it.

**Comment by bachig26** [comment]
sorry about that, i just found that my AriaNG web version is also not working.

can you let me know, what settings that I need to define to make it work from the fresh start?

**Comment by mayswind** [comment]
there are many videos or articles about how to set aria2 and AriaNg in the web, and you can just use keyword "aria2" and "AriaNg" to search

**Comment by sedlund** [comment]
@bachig26 check out https://github.com/agalwood/Motrix  -- it just works

**Comment by necros2k7** [comment]
I also can`t install where aria2.exe goes to? Pls make step by step guide for Win.

**Comment by mayswind** [comment]
> I also can`t install where aria2.exe goes to? Pls make short guide for Windows build.

for any issues about aria2, please goto https://github.com/aria2/aria2/issues for help
