### ISSUE TITLE
Task Detail Page shows No Chart Data Bug

### ISSUE THREAD

**Issue by hl2guide** [mayswind/AriaNg-Native#103]
The Task Detail Page shows no Chart Data and then does not update data.

**Comment by mayswind** [comment]
could you provide the reproducing method?

**Comment by hl2guide** [comment]
1. Add a new download
2. Start the download
3. On the downloads page (index.html#!/downloading), hover over the task list item and click the right facing arrow
4. View the chart

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/203284175-2cf3b3f3-a041-4c78-a93d-86c481b0405b.png)
do you set this option to disabled? and could you upload a screenshot?

**Comment by hl2guide** [comment]
setting:
![setting](https://user-images.githubusercontent.com/17044982/203293734-f6002407-623e-42be-9588-fdc3c017ed64.jpg)
screen:
![screen](https://user-images.githubusercontent.com/17044982/203293720-d384f249-efe1-4498-84b0-a7a247dec873.jpg)

**Comment by mayswind** [comment]
I cannot reproduce your problem. I have three questions.
1. Do all tasks have this problem?
2. Does this problem occur every time or some times?
3. Does other items in the task detail page be updated when the chart has no data?

**Comment by hl2guide** [comment]
A1) Yes
A2) Every time
A3) No

After more testing it seems to be a connection issue related to Windows 11 22H2.
