### ISSUE TITLE
'Task Details' do not update

### ISSUE THREAD

**Issue by Spainman** [mayswind/AriaNg-Native#104]
Switching to the details of a running task everything is static, does not update:
- all values in 'overview' stay the same although the download is progressing
- the pieces chart does not change
- in the files pane the progress does not change
- 
Running v1.3.2 (350b71e) on Win10

(Note: Aria (non-native) v1.3.2e (c7ed84d) updates everything as expected)

Edit: All three 'Updating **** Interval' settings are set @ 1s, and not disabled.

**Comment by mayswind** [comment]
does the information in task list page update?

**Comment by Spainman** [comment]
Yes, the task list updates the download status just fine.
It's just the per-task detail pages that are 'static'. They show the status of the moment when the details are opened and don't change.

**Comment by mayswind** [comment]
Can you run AriaNg Native in development mode, and provide more details? You can modify AriaNg Native properties, and append " --development" in target.

![image](https://user-images.githubusercontent.com/2211648/210213473-a43121d7-143e-4249-acac-a2850ade45c2.png)

Then, open "AriaNg Debug Console", and click "Open Browser DevTools"

![image](https://user-images.githubusercontent.com/2211648/210214211-8104a85e-2fee-44ab-bd5d-ed299b3eddc8.png)

Then, click "Console", and check whether there is some error in the below.

![image](https://user-images.githubusercontent.com/2211648/210214537-b2bbdfa6-33b3-4fd8-9066-2e45b80e345a.png)

**Comment by mayswind** [comment]
The latest AriaNg Native 1.3.3 has fixed this problem
