### ISSUE TITLE
Shortcomings in excellent software and some suggestions

### ISSUE THREAD

**Issue by Master-Panda** [mayswind/AriaNg-Native#107]
Hello sir, can you add a function to automatically open aria2 when opening ariang native, and also close aria2 when closing ariang? In addition, I think the management of the download list by ariang is a little unreasonable. For example, when deleting a task, you need to delete it twice, and there is no function to delete the task and delete the local file at the same time, and there is no function to quickly open the folder through the download list. I hope you can see it and adopt it. Thank you

**Comment by mayswind** [comment]
1. AriaNg Native has already supported executing command on startup and terminate it when exiting AriaNg Native.
2. I don't know what you mean about deleting twice. When you delete a non-running task, you just click delete and it will be deleted from the list. If you delete a running task, aria2 would set the task status to deleted.
3. aria2 does not support delete files from file system. duplicated with https://github.com/mayswind/AriaNg/issues/11
4. I think opening the download folder in task list page is not a
