### ISSUE TITLE
请问这个启动时执行命令应该怎么设置呢

### ISSUE THREAD

**Issue by Master-Panda** [mayswind/AriaNg-Native#108]
请问
<img width="548" alt="gYQvEMt27O" src="https://user-images.githubusercontent.com/100832281/216993832-b4e28c29-fb7f-4917-8d71-c9ef20922b3a.png">
这个启动时执行命令应该怎么设置呢

**Comment by mayswind** [comment]
点击“浏览”，找到应用程序，点击“打开”。

**Comment by Master-Panda** [comment]
你好我选中的是bat文件或者vbs文件，没打开












小芒果🥭
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月7日(周二) 凌晨0:48
收件人: ***@***.***&gt;;
抄送: "Master ***@***.******@***.***&gt;;
主题: Re: [mayswind/AriaNg-Native] 请问这个启动时执行命令应该怎么设置呢 (Issue #108)




 
点击“浏览”，找到应用程序，点击“打开”。

**Comment by mayswind** [comment]
启动参数最后追加 " --development"
![image](https://user-images.githubusercontent.com/2211648/210213473-a43121d7-143e-4249-acac-a2850ade45c2.png)

然后启动后打开 "AriaNg 调试控制台"，然后有启动执行命令的输出情况，可以打开看一下。
![image](https://user-images.githubusercontent.com/2211648/210214211-8104a85e-2fee-44ab-bd5d-ed299b3eddc8.png)

**Comment by Master-Panda** [comment]
你好作者，我试了下似乎还是不行







小芒果?
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mayswind/AriaNg-Native"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月15日(星期三) 晚上6:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mayswind/AriaNg-Native] 请问这个启动时执行命令应该怎么设置呢 (Issue #108)





 
启动参数最后追加 " --development"
 
 
然后启动后打开 "AriaNg 调试控制台"，然后有启动执行命令的输出情况，可以打开看一下。

**Comment by mayswind** [comment]
你看看调试控制台中显示的内容啊。。。不是让你试试行不行

**Comment by Master-Panda** [comment]
小芒果?
***@***.***







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mayswind/AriaNg-Native"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月16日(星期四) 中午11:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mayswind/AriaNg-Native] 请问这个启动时执行命令应该怎么设置呢 (Issue #108)





 
你看看调试控制台中显示的内容啊。。。不是让你试试行不行
