### ISSUE TITLE
AriaNg Native 重試下載一直失敗

### ISSUE THREAD

**Issue by cj-neo** [mayswind/AriaNg-Native#109]
原本使用 AriaNg Native 1.2.3 版，今天心血來潮下載 1.3.2 版來用，結果發現
因為 503 （估計是流量過高）下載失敗的檔案，按下重試之後還是無法下載，
但複製連結，手動下載卻可以，試過很多個檔案都是這樣，

我把版本改回 1.2.3 也是一樣的情形耶 @@"
感覺有可能是我自己環境的問題！
執行過程如下：

![DEMO](https://user-images.githubusercontent.com/35209118/220350212-d5845708-c24e-4c2f-a9c4-4c06c9db9db3.gif)

**Comment by mayswind** [comment]
下载问题找aria2问问？
