### ISSUE TITLE
AriaNg Native 1.32 版的失败项目重试功能真的有问题!!

### ISSUE THREAD

**Issue by cj-neo** [mayswind/AriaNg-Native#111]
这个问题卡两三星期了，上次以为是我自己环境的问题，您也回覆说应该找 ARIA2 问才对，
后来我确定不是 ARIA2 本身的问题，于是今天又试了一下：

同一台下载主机，用 http://ariang.mayswind.net/latest 这个 DEMO 网址进行失败项目重试结果没问题！
然后我又下载了上一版（1.24 版），重试了失败项目也是没问题！
我再下一次 1.23 版，发现重试了失败项目还是没问题！

我又怀疑是不是某个设定值导致冲突，于是进行 "清除设定历史" 然后 "重设设定"
再重新载入 AriaNg Native 1.32 版，但发现还是无法重试失败项目。

因此几乎可以推断，确实是 AriaNg Native 1.32 这个版本的问题了。
有时间的话可能要请大大检查一下，感恩！

PS.上次说 1.23 版，也有同样问题是不对的，那是因为我没有把常驻的 1.32 版关闭（以为跑 1.23 其实还是 1.32）

尝试画面如下：

![220350212-d5845708-c24e-4c2f-a9c4-4c06c9db9db3](https://user-images.githubusercontent.com/35209118/224487796-8e2a9d9f-0f12-41af-ba4e-18b12bcb370d.gif)

**Comment by mayswind** [comment]
我按你的截图无法复现问题，需要你提供更详细的复现步骤。
或者你可以在 AriaNg Native 的快捷方式后加上“ --development”，打开调试控制台（参考 #104），在“最近100条日志”中找到错误信息，然后把报错信息贴到这里。

**Comment by cj-neo** [comment]
> 我按你的截图无法复现问题，需要你提供更详细的复现步骤。 或者你可以在 AriaNg Native 的快捷方式后加上“ --development”，打开调试控制台（参考 #104），在“最近100条日志”中找到错误信息，然后把报错信息贴到这里。

好的，我看到调试控制台了，不过之前的错误很早就被清掉了，等我这边出现新的下载错误，再把错误信息贴给您！
谢谢

**Comment by cj-neo** [comment]
抓到了！ 报错信息如下：

跑出一个警告和一个错误

![image](https://user-images.githubusercontent.com/35209118/224534789-ce6f02ee-5b3f-401e-840a-53013f0aa573.png)

警告详情

![image](https://user-images.githubusercontent.com/35209118/224534936-629925f0-1ef7-4a5e-a465-37a3b5821e3a.png)

错误详情

![image](https://user-images.githubusercontent.com/35209118/224534946-24e4bbde-f949-448b-bbb8-d2ff51f53b8d.png)

Console

![image](https://user-images.githubusercontent.com/35209118/224534805-9d944c58-7c3f-4e5a-b2ce-23ff5db49c40.png)

![image](https://user-images.githubusercontent.com/35209118/224535130-11dddd85-ee1a-4997-b16a-88c0c3dfcc59.png)

**Comment by cj-neo** [comment]
我把主机连线资讯发给你邮箱了，直接连接我主机测试好了！不过请不要删掉正在下载的东西哦，谢谢！

**Comment by mayswind** [comment]
@cj-neo 感谢您的反馈，但是您的ip我确实连不上。您下次出问题的时候能帮截一条这个的内容么？
![image](https://user-images.githubusercontent.com/2211648/224537869-07f79d76-43c9-4587-8c23-ea777635d5b5.png)

**Comment by cj-neo** [comment]
应该是您的ISP不支持IPV6，试试IPV4，如果还不行就是被墙了，因为我在台湾环境不太一样 @@"

158.101.21.193

mayswind ***@***.***> 於 2023年3月12日 週日 下午6:07寫道：

**Comment by mayswind** [comment]
今天新发布的1.3.3版本已经修正了该问题

**Comment by cj-neo** [comment]
好的，非常感謝！
