### ISSUE TITLE
macOS Application Signing

### ISSUE THREAD

**Issue by razvanazamfirei** [mayswind/AriaNg-Native#112]
Hi there,

Your application is included in homebrew-casks. During the last update, we discovered that the application is currently unsigned; macOS on ARM requires all applications to be signed. Would you be able to sign future releases of your application? Thank you!

Homebrew/homebrew-cask/pull/142965

**Comment by mayswind** [comment]
AriaNg Native does not provide official macos arm64 package now

**Comment by mjgardner** [comment]
> AriaNg Native does not provide official macos arm64 package now

Fair, and the x86_64 version can *technically* still run on arm64 via the [Rosetta software that macOS installs the first time one tries to open an app that needs it](https://support.apple.com/en-us/HT211861).

But macOS *will not run unsigned software* unless the user allows it in their System Settings and acknowledges a warning that also offers to move the app to the Trash, [as described here](https://support.apple.com/en-us/HT202491#:~:text=If%20you%20want%20to%20open%20an%20app%20that%20hasn%E2%80%99t%20been%20notarized%20or%20is%20from%20an%20unidentified%20developer).

<img width="261" alt="macOS warning about possible malware in AriaNg Native" src="https://github.com/mayswind/AriaNg-Native/assets/133483/7685d0c6-d50e-4e35-ae94-31d245076795">

[As of January](https://www.theverge.com/2023/1/17/23558708/apple-mac-mini-intel-silicon-arm-based-m2), all currently-shipping Macs are on arm64 save one: the [2019 build-to-order Mac Pro](https://support.apple.com/kb/SP797). It is (over)due for [an arm64 replacement this year](https://www.macrumors.com/guide/2022-mac-pro/).

An x86_64-only macOS package serves a dwindling niche of discontinued models and discontent professionals. AriaNg Native is unusable for most users who want to maintain their Mac's security. Please consider [signing and notarizing the macOS package](https://www.electronjs.org/docs/latest/tutorial/code-signing#signing--notarizing-macos-builds).
