### ISSUE TITLE
Request for transparency

### ISSUE THREAD

**Issue by sedlund** [mayswind/AriaNg-Native#113]
Hello

I had my comment marked as spam here:

https://github.com/mayswind/AriaNg-Native/issues/101#issuecomment-1424633564

I would like to know the github user account that did so.

My comment was in support of the issue raiser and their best interest.

Please provide their github account id name in the name of transparency for github and your project.  If you do not provide it I will ask Microsoft.

Thanks.

**Comment by mayswind** [comment]
I mark this comment spam, because this comment is not releated to the topic or AriaNg Native. This comment is not help to the AriaNg Native users.
