### ISSUE TITLE
How to keep aria rpc server always connected?

### ISSUE THREAD

**Issue by silverdragon70** [mayswind/AriaNg-Native#114]
I installed ariaNG Native and run the aria2 in cmd through command aria2c --enable-rpc
And the AriaNG Native shows that it is connected to the rpc server
But once I close the cmd window , the software lose connection to aria and be not functioning
What should I do keep it functioning and connected ,rather than keeping cmd window active?
How to keep aria rpc server functioning in background without active cmd window?
And without being have to reopen aria rpc server each time I restart my computer?
Is there any additional software to install ?

**Comment by mayswind** [comment]
You should go to https://github.com/aria2/aria2/issues for help, or you can use "execute command on startup" to open aria2 automatically when you open AriaNg Native like the below
![image](https://user-images.githubusercontent.com/2211648/226612454-ce3852bb-0632-4259-8b7b-3cf6b448dd26.png)
