### ISSUE TITLE
BT种子下载能不能直接省过确认下载所有文件

### ISSUE THREAD

**Issue by WANGWANGSUIBINGBING** [mayswind/AriaNg-Native#115]
每下一个种子还需要手动点击立即下载，想要批量下载种子任务无法实现，通过命令行也是一样的效果，这样的话就没办法实现批量下载了，感觉命令行下载BT时也没什么优势了，都还需要手动点立即下载才能下载任务

**Comment by mayswind** [comment]
既然你的需求是不需要界面，那为什么不直接用aria2的命令行...

**Comment by WANGWANGSUIBINGBING** [comment]
/

**Comment by WANGWANGSUIBINGBING** [comment]
..其实aria2c的命令行我看了很多文章也没有搞懂怎么用它通过rpc推送到远程，如果你能告诉我，我会非常感谢🙏🏻。

**Comment by mayswind** [comment]
aria2的命令行不能通过jsonrpc调用远端的aria2，但是如果用命令行脚本的话，有python或nodejs的库或cli工具可以实现。甚至bash里直接通过调用http接口也是可行的。
