### ISSUE TITLE
how to set up aria2

### ISSUE THREAD

**Issue by cyberhardt** [mayswind/AriaNg-Native#116]
how to setup aria2? no instructions anywhere.

**Comment by cyberhardt** [comment]
ok, apparently you need to type aria2c --enable-rpc --rpc-listen-all on cmd. that's very inconvenient, having to keep a cmd window open every time you wanna use the program. why not include it with the download manager?

**Comment by mayswind** [comment]
AriaNg Native is just an aria2 frontend, and the aim of AriaNg Native is not becoming a completed download tool but making aria2 eaisier to use. If you want a completed download tool, I think there are many other choices for you, including someone based on aria2.
By the way, AriaNg Native supports "Execute Command on Startup" (see the below screenshot). I think you can use this feature.
![image](https://user-images.githubusercontent.com/2211648/236624880-e5daecfa-d0a4-445f-afce-e2ea83532001.png)
