### ISSUE TITLE
关于反向的预设排序

### ISSUE THREAD

**Issue by fondplay-neo** [mayswind/AriaNg-Native#120]
又发现一个问题就是预设排序的方式没办法反向，因为其他排序方式都有显示栏位，只要在栏位上点一下就可以反向排序
所以是否考虑增加一个栏位并把 "预设" 这个名称改成 "依加入时间" 这样排序方式一目了然，而且也可以切换反向排序了！

需求是这样的，因为我都会去 "正在等待" 这个清单确认档案是否正确加入，但是当清单太长的时候新加入的档案因为在最下面，
必须一直用鼠标滚轮卷动页面才能看到最新加入的档案十分不便，所以希望能反向排序让最新加入的档案显示在最上面（目前很多论坛或留言版也是这样设计），所以又要麻烦大大有空的时候考虑是否修改一下，万分感激！

**Comment by mayswind** [comment]
默认指的是没有排序的意思，不会为默认增加反向排序。
