### ISSUE TITLE
Please support macOS arm64

### ISSUE THREAD

**Issue by xiaozhuai** [mayswind/AriaNg-Native#123]
Electron has already support macOS arm64, please support macOS arm64.

I see arm64 is already in arch in `electron-builder-mac.json`, but it seems not working.
<img width="898" alt="image" src="https://github.com/mayswind/AriaNg-Native/assets/4773701/80497ce8-1037-4dce-a824-622671d8234b">

**Comment by mayswind** [comment]
AriaNg Native does not provide official macos arm64 package now. You can build it by youself

**Comment by xiaozhuai** [comment]
@mayswind 
Thank you for your great work!
BTW, what about setup github actions for building all the package?
