### ISSUE TITLE
Where is the UI expecting to find aria2?

### ISSUE THREAD

**Issue by porkchoppie** [mayswind/AriaNg-Native#124]
I have tried both ng as well as this app, and keep getting this error. 

<img width="465" alt="Screenshot 2024-07-02 at 7 27 52 AM" src="https://github.com/mayswind/AriaNg-Native/assets/158986366/d4c2d3b3-56d1-450e-9c0c-3c279721a124">

So I assume it is a path issue, or there is some other root cause.

**Comment by mayswind** [comment]
duplicate with https://github.com/mayswind/AriaNg/issues/755
