### ISSUE TITLE
Windows 'unrecognized application' Intercept

### ISSUE THREAD

**Issue by UnaHe** [mayswind/AriaNg-Native#13]
Self-extracting program Windows prompt 'unrecognized application', it is recommended to put the archive directly
![qq 20180309114304](https://user-images.githubusercontent.com/30680842/37189396-1ec66f50-238f-11e8-861a-e782376ca175.png)

**Comment by mayswind** [comment]
Please add screenshots

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/41450296-4003e240-7099-11e8-9155-48ef6341be16.png)
