### ISSUE TITLE
Save preferences

### ISSUE THREAD

**Issue by TheNocturnalEvil** [mayswind/AriaNg-Native#14]
How to save my Aria2 settings?
Because each time I leave the settings menu they're just reset to default values.

**Comment by mayswind** [comment]
The settings you changed in AriaNg will be saved immediately. But if you restart aria2, the changes of aria2 settings will lose.

**Comment by TheNocturnalEvil** [comment]
No still not working. Leave it I uninstalled it and Aria2 and went for Folx Pro. Looks like this software isn't ready yet for general usage and Aria2 itself ain't that fast either.
