### ISSUE TITLE
为什么我运行0.4.0界面一片空白？

### ISSUE THREAD

**Issue by ihuc** [mayswind/AriaNg-Native#16]
为什么我运行0.4.0界面一片空白？

**Comment by mayswind** [comment]
更多信息？

**Comment by ihuc** [comment]
win64 奇怪的是我可以运行0.2.0，最新版打开就是空白界面

**Comment by mayswind** [comment]
从github的release里下载的还是自己编译的？

**Comment by mayswind** [comment]
能提供下截图么？

**Comment by ihuc** [comment]
![snipaste_2018-08-02_10-30-00](https://user-images.githubusercontent.com/15769683/43559095-140de188-963f-11e8-9af4-644bec05b785.png)

**Comment by yinfxs** [comment]
我mac自己编译的也是一片空白
![image](https://user-images.githubusercontent.com/6890643/44615439-ca5fa400-a86c-11e8-9cd9-82b26b3bd209.png)

**Comment by mayswind** [comment]
@yinfxs 你看下源文件目录下app目录下有文件么

**Comment by yinfxs** [comment]
我下载release的正常了

**Comment by cortney-x** [comment]
怎么用不了啊

**Comment by ikakaxi** [comment]
我mac自己编译的也是一片空白

**Comment by ikakaxi** [comment]
我看上面的说release可以，我下载release也可以用了，自己编译的不行
