### ISSUE TITLE
How can I save settings?

### ISSUE THREAD

**Issue by ahmedtds** [mayswind/AriaNg-Native#17]
I run aria2, then I open AriaNG native, change some advanced settings etc..
Then I close ariang and aria2
When I open them again, all my settings are gone.
How can I make these settings permanent?
I thought maybe "Save session" button would do it but whenever I click it, it says "Filename is not given"
What does that mean? There's no input to give a filename or anything, it always give that error.

Using Windows btw.

Can you help please? Thanks!

**Comment by mayswind** [comment]
1, aria2 does not support save settings via rpc, so you should modify aria2.conf and save it.
2, Can you provide a screenshot about "Save session" problem?

**Comment by candrapersada** [comment]
how to modify aria2.conf
![103753121-39548680-503d-11eb-8ef6-5c653342d864](https://user-images.githubusercontent.com/36833664/103955606-44143600-5179-11eb-8852-996611a8f946.png)
