### ISSUE TITLE
SERVER 下拉清單

### ISSUE THREAD

**Issue by cj-neo** [mayswind/AriaNg-Native#21]
希望 SERVER 的下拉清單可以捲動和排序，第一個希望是因為 RPC SERVER 太多的時候只能看到並控制部分(如附件圖片所示)，第二個希望也是一樣如果 SERVER 一多沒有排序會很混亂難找，所以希望未來的版本可以依照名稱排序一下，感謝! ^^"

PS.希望下拉清單可以用滑鼠滾輪捲動、另外清單可以用"自然排序"的方式來排，當然以上只是建議拉 XD

![1](https://user-images.githubusercontent.com/35209118/44007765-b24ea544-9ecd-11e8-8f74-c0db514b5b08.png)

**Comment by mayswind** [comment]
最新的daily build已经支持下拉清单用鼠标滚动，以及在设置中可以设置rpc列表的排序方式。
