### ISSUE TITLE
匯出、匯入設定

### ISSUE THREAD

**Issue by cj-neo** [mayswind/AriaNg-Native#22]
希望能增加匯出、匯入設定的功能，不然電腦重裝又要重新輸入所有的 SERVER 設定一次，想到就可怕

![2](https://user-images.githubusercontent.com/35209118/44008833-2dc12cc2-9eda-11e8-9776-ea18144ee81b.png)

**Comment by mayswind** [comment]
最新的daily build已经支持。

**Comment by cj-neo** [comment]
感謝! 修改的速度真快，太厲害了，只是小弟沒找到 AriaNg-Native 的 daily build 只有 AriaNg 的? 謝謝囉

**Comment by mayswind** [comment]
AriaNg Native不会发布后自动打包，需要的可以自己拉下代码进行编译。或者等几天发0.5就有release的可执行文件了。

**Comment by cj-neo** [comment]
謝謝，那我等下個版本好了 ^^

**Comment by mayswind** [comment]
@cj-neo 新版本已经发布了，可以更新了
