### ISSUE TITLE
能加个快捷指定下载目录功能吗？

### ISSUE THREAD

**Issue by ystyle** [mayswind/AriaNg-Native#23]
我想在下载到conf设定目录的子目录下边
比如我在conf文件设置的目录很长。 每次要重新输入默认目录。。。

AriaNg 新建下载设置里的`下载路径` 只是个提示， 输入东西后就不见了， 而且这样默认输入的目录，是在aria2的安装目录下载的。

我想`下载路径` 能否改成默认值就是conf设置的路径，我直接在后面加子路径就就好了

**Comment by mayswind** [comment]
最新的AriaNg会记录最近使用过的下载目录地址，点击下载目录可以选择。
