### ISSUE TITLE
關於新版的小建議

### ISSUE THREAD

**Issue by cj-neo** [mayswind/AriaNg-Native#24]
剛剛試用了 0.5 新版，關於之前建議的功能都加上去了，實在是非常感謝!!
只是還有兩個小小的建議

1.左上的 RPC 清單現在除了下拉還可以捲動了實在非常方便，但顯示範圍能否再加大一些呢，舊版雖然
不能拖曳但是可以幾乎把顯示的高度佔滿，新版卻只用了不到一半的高度感覺有點浪費了，所以希望下個版本顯示面積能再加大一點或者自適應高度占滿 ...

2.另外現在排列順序也可以用了但還是希望能採用"自然排序的方式"，否則就會像下面圖片那樣
k2 跑到 k19 和 k20 中間去了，當然也可以手動處理補零(變成 k02) 排序就會正確了 ... 

當然以上只是本人的希望，因為我也是程序員習慣吹毛求疵，其實現在已經很好用啦 XD

![1](https://user-images.githubusercontent.com/35209118/44623969-d18cbd80-a911-11e8-8cf0-8386a6eea56a.png)

**Comment by mayswind** [comment]
1, AriaNg Native 允许设置的纵向高度最小时刚好能显示到“Aria2 状态”那里，所以RPC 列表设置的此高度。
2, 目前是简单判断两者的顺序，未来会调研主流操作系统中的排序方式再来确定是否要调整。

**Comment by cj-neo** [comment]
1.請問為什麼要設置最小高度而不是最大呢，畢竟一般使用的時候都不會顯示只有需要切換的時候才會去點，而且點完就自動消失了，所以並不會占空間。
2.常見的 WINDOW 作業系統就是用自然排序呢!

對了，原本的清單順序是依據 "最近使用"，其實這和依據 "RPC 別名" 並不衝突，建議可以把目前使用的 RPC SERVER 放在下拉清單內的垂直置中(或者記憶上次關閉時清單捲動的位置)，因為一般維護都是依據順序維護(例如 K19 再來就是 K20 這樣 ... 如果一打開清單就顯示在 K19 的位置那要點 K20 就很快了，目前是點了 K19 之後下次打開就必須再從 K01 捲動到 K20 這樣。

最後再次感謝您的大恩大德，這個軟件幫了小弟不少忙呢 :P

![2](https://user-images.githubusercontent.com/35209118/44626567-269bf400-a951-11e8-8078-a452eaf50463.png)
)

**Comment by mayswind** [comment]
1, 因为现在 AriaNg Native 的开发工作很初级，没办法把当前窗口的高度告知 AriaNg，所以采取的是兼容最小高度的方式
3, 很少有见应用是这样做的，不支持这种方案

**Comment by mayswind** [comment]
排序方式会在下个版本中调整为自然排序，今天的AriaNg daily build已经更新。
