### ISSUE TITLE
關於重試下載的建議

### ISSUE THREAD

**Issue by cj-neo** [mayswind/AriaNg-Native#25]
目前重試下載好像是會建立一個新任務，建議把舊任務刪除了吧，不然很多要重試的話容易造成混亂呢，而且如果大量任務要重試，一個一個手動去刪除也是很麻煩(用 ARIA2 下載百度盤因為很慢都一次下載大量卻又常常容易失敗需要重試 ...)

另外刪除 BT 斷種的任務，好像只會刪除列表，不會真正從硬盤中刪除檔案必須手動再去刪除? 這好像是 ARIA2 先天的問題還是我不會設定 @@"

謝謝!

**Comment by mayswind** [comment]
1, 
![image](https://user-images.githubusercontent.com/2211648/44626694-682d9e80-a953-11e8-8795-c3ac65745334.png)
2, 批量重试在考虑 mayswindAriaNg#136
3, 是这样的，提问前请搜索已有issues，mayswind/AriaNg#11

**Comment by cj-neo** [comment]
了解，謝拉

**Comment by dshame** [comment]
关于bt或者pt下载任务出错。在aira2网页上看到有一个可以恢复的选择，check-integrity =true这个选项。  

![photo_2018-10-28_05-08-00](https://user-images.githubusercontent.com/26822775/47609414-983b1000-da70-11e8-9378-a9f0f22a8c47.png)
按照说明，恢复bt或者pt任务需要提供散列哈希或者整个文件的哈希，如果是提供散列哈希则可以恢复任务进度，如果是提供整个文件的哈希则从文件的大小判断是不是下载完成，（这里感觉有点不合理，不是用哈希校验文件判断下载是不是完成，显然没有选择none的分配方式都会分配到一样的空间大小），散列校验失败重新开始任务。
![photo_2018-10-28_04-47-36](https://user-images.githubusercontent.com/26822775/47609523-da655100-da72-11e8-9bb5-65d685bed6e3.png)  
很多时候重启aria2软件时，或者不可抗拒的使用脚本断开重启时，那些没来得及连接ssh删除的种子文件以下载好的任务状态出现在做种或者完成的列表里。显然文件是损坏的。希望作者能在错误列表给种子任务重试的按钮，当然能恢复下载进度最好了，不能恢复最好能加一个判断，比如重试马上返回完成，或者做种的状态，就可以删除原来的文件重新开始任务。感谢

**Comment by mayswind** [comment]
@dshame 这个问题请去aria2的issues去提

**Comment by dshame** [comment]
我会的
