### ISSUE TITLE
運行 0.5 版之後再運行 0.4 版原先的設定都跑掉了

### ISSUE THREAD

**Issue by cj-neo** [mayswind/AriaNg-Native#26]
今天運行了 0.5 版(有繼承 0.4 版設定)，但關閉 0.5 版後再打開 0.4 版發現原先的設定都不見了 ... 怎會這樣呢，請問該怎處理才能取回 0.4 版的設定，感恩

**Comment by mayswind** [comment]
AriaNg Native不能保证打开不同的实例存取相同的配置。
