### ISSUE TITLE
为什么建议解压 AriaNg-0.5.0.exe 呢

### ISSUE THREAD

**Issue by EdenHell** [mayswind/AriaNg-Native#27]
![image](https://user-images.githubusercontent.com/5779655/45153847-0fd68680-b208-11e8-80f6-82349f1c01eb.png)
也就是说建议解压 AriaNg-0.5.0.exe\$PLUGINSDIR\app-32.7z 直接使用吗？
为何不直接提供压缩文件而是自解压文件呢。或者提供两种：AriaNg-0.5.0.exe、AriaNg-0.5.0.zip

**Comment by mayswind** [comment]
解压AriaNg-0.5.0.exe，这是个自解压文件，不解压可以运行，解压后运行速度更快，没必要再提供一个zip文件了。
