### ISSUE TITLE
为什么不显示进度

### ISSUE THREAD

**Issue by xivi1839** [mayswind/AriaNg-Native#37]
就是下载MP4格式的文件不显示进度条？ 这里怎么上传图片，不会呀

**Comment by mayswind** [comment]
1、跟文件格式无关，截图吧。2、把图片内容在文本框里粘贴。

**Comment by Josie915** [comment]
![1111](https://user-images.githubusercontent.com/24610024/50311935-ce7d9480-04e1-11e9-9aa5-6f3265a2d4f1.png)
就是这样，但是下载数字一直有不停的变动，进度条永远都是0%

**Comment by mayswind** [comment]
点进去看已下载是有增加么
