### ISSUE TITLE
能否支持点击打开文件和开机自动启动

### ISSUE THREAD

**Issue by xtrats** [mayswind/AriaNg-Native#38]
好像所有的aria 界面都没有这两个功能

**Comment by underlaw** [comment]
肯定支持不了，这是web端关联不了文件格式，开机更不可能

**Comment by mayswind** [comment]
其实能。但是这个项目没有时间维护了。其他人来提pr吧。

**Comment by mayswind** [comment]
AriaNg Native 已经支持命令行打开文件了，只要配置好注册表就可以双击启动或唤醒AriaNg Native创建新任务了。开机自动启动自己放到启动文件夹里就可了，AriaNg Native不再提供单独的参数设置。
