### ISSUE TITLE
Icon Problem

### ISSUE THREAD

**Issue by nclmrc** [mayswind/AriaNg-Native#41]
there isn't any icon

**Comment by mayswind** [comment]
Please provide the screenshot and the information of your operation system.

**Comment by nclmrc** [comment]
![immagine](https://user-images.githubusercontent.com/38593316/55730340-3c5db580-5a18-11e9-8956-b0095905c5e1.png)
windows 10

**Comment by mayswind** [comment]
Could you provide more information (the version of AriaNg Native, which package you use, the way you install or open AriaNg Native, ...) or how to reproduce it?

**Comment by nclmrc** [comment]
AriaNg-Native
rc 1.0.2

**Comment by mayswind** [comment]
Do you use the pre-built release or you build AriaNg Native by yourself? And which package do you download? What is your screen resolution and dpi settings?

**Comment by nclmrc** [comment]
i use this installer https://github.com/mayswind/AriaNg-Native/releases/download/1.0.2-rc1/AriaNg-Native-1.0.2-RC1-Windows-x64.msi
1920x1200 dpi i don't know

**Comment by mayswind** [comment]
AriaNg Native 1.0.3 rc1 has been released. You can download and install it and check if the icon problem is sloved.

**Comment by nclmrc** [comment]
same problem. at the first run it's ok. if i close and reopen it, the problem is present

**Comment by mayswind** [comment]
I'm afraid I cannot reproduce and solve your problem. I suggest you can use another computer or reinstall your operation system.

**Comment by nclmrc** [comment]
same problem on another pc with win7

**Comment by mayswind** [comment]
@nclmrc I reproduced this problem today. At the same time, I find ico file cannot be displayed very well too. If you still have this problem, I suggest you can fix ico file problem or rebuild your icon cache.
