### ISSUE TITLE
1.0.3 RC1版本从休眠状态中开机将100%无法重新连接aria2

### ISSUE THREAD

**Issue by Mosney** [mayswind/AriaNg-Native#43]
一直习惯用休眠代替关机，最近换了1.0.3RC1版本，右上角X按钮变成了最小化到状态栏后偶然发现休眠开机之后不能重新正常连接aria2，关闭重开可以解决，不清楚之前的Native版本是否有这个Bug。

**Comment by mayswind** [comment]
之前版本没有最小化到tray或dock的功能。你是用websocket的方式连接的么？websocket的话是有目前可能有这种问题的，可以换成http方式。

**Comment by Mosney** [comment]
> 之前版本没有最小化到tray或dock的功能。你是用websocket的方式连接的么？websocket的话是有目前可能有这种问题的，可以换成http方式。

是这样的，用的wss

**Comment by mayswind** [comment]
嗯。如果能改成http先改成http用吧。websocket现在AriaNg没支持重试功能，之后评估下这块。

**Comment by mayswind** [comment]
最新的代码已经支持使用websocket时自动重连功能
