### ISSUE TITLE
功能需求

### ISSUE THREAD

**Issue by zcmarkyoung** [mayswind/AriaNg-Native#44]
1、能否在安装过程中提供设置设置安装目录支持。
2、windows的对aria2设置无法保存。
3、能否下载项目（未完成）进行参数调整，比如设置cookie,设置user-agent，现有设置是针对全局设置的。

**Comment by mayswind** [comment]
1, 不能
2, 不能，aria2不提供这样的接口，无法实现
3, 现在创建任务的时候有在选项中可以设置http头

**Comment by zcmarkyoung** [comment]
3.中可以在创建任务后再进行编辑吗？

**Comment by mayswind** [comment]
3. AriaNg上如果标灰了就不行，如果没标灰就行。标灰与否是根据aria2是否支持来设计的。
