### ISSUE TITLE
非全屏状态下不显示箭头

### ISSUE THREAD

**Issue by 1349422030** [mayswind/AriaNg-Native#46]
非全屏
![图片](https://user-images.githubusercontent.com/35253997/56863294-3ccde880-69e7-11e9-9804-2792e274c64c.png)

全屏
![图片](https://user-images.githubusercontent.com/35253997/56863296-41929c80-69e7-11e9-8860-9e9bec66b105.png)

**Comment by mayswind** [comment]
限制了当宽度>=992px的时候才会显示，避免影响下载速度那一栏。
