### ISSUE TITLE
macOS 10.14.4 每次关闭都弹窗报错

### ISSUE THREAD

**Issue by goolhanrry** [mayswind/AriaNg-Native#48]
<img width="532" alt="屏幕快照 2019-05-13 21 04 49" src="https://user-images.githubusercontent.com/22849092/57623689-dc33d380-75c2-11e9-9d87-51d6eae67c9b.png">

**Comment by mayswind** [comment]
使用的AriaNg Native的版本是？以及有复现步骤么。我这目前无法复现这个问题。

**Comment by goolhanrry** [comment]
报错的版本是1.1.0，之前使用0.5.0的时候完全正常。我的node版本是12.1.0，不知道这个对你有没帮助。

复现步骤就是只要软件在运行中，任何时候在dock上右键点击图标-退出，马上报错。

**Comment by WisdomKwan** [comment]
Windows版本每次打开都有这个错误：

![批注 2019-05-22 000855](https://user-images.githubusercontent.com/1547241/58112334-e179c980-7c25-11e9-8688-23f817be8cfa.jpg)

**Comment by mayswind** [comment]
@WisdomKwan 按你的步骤没有复现这个问题。

**Comment by WisdomKwan** [comment]
@mayswind 前天可以不停的打开新窗口，右下角会出现很多小图标，每一次打开都会出现错误提示，今天试了一下，只能打开一个了，也没有复现。

**Comment by BrightVan** [comment]
我也会这样。只是打开一个啊，没有多个在运行。每次退出都会提示。

**Comment by mayswind** [comment]
@goolhanrry @WisdomKwan 前两个图的问题目前复现不了，尝试性调整了下，不知是否有效果。
@BrightVan 你的问题不知与前两个图是否一样。此外，目前已知macOS下有另外的一个问题，怀疑electron 5.x有bug（降级到electron 4.x不会复现），有问题的可以降级到AriaNg Native 1.0.3（AriaNg Native 1.0.3 使用的 electron 4.1.4）。

**Comment by BrightVan** [comment]
升级到V1.1.1问题依旧
![image](https://user-images.githubusercontent.com/9381559/58524075-89c8f880-81f9-11e9-9399-84cd1e0918bc.png)

**Comment by mayswind** [comment]
@BrightVan 你试试把AriaNg Native整个都卸载了再重新安装试试呢？

**Comment by BrightVan** [comment]
使用Appcleaner卸载了，问题依旧。

**Comment by mayswind** [comment]
@BrightVan 刚重新检查了次上传的包，发现macOS的包里的代码不是最新的，现在已经重新上传了。麻烦再验证下吧。实在抱歉。

**Comment by BrightVan** [comment]
OK了。
