### ISSUE TITLE
希望增加一个选项，决定是否驻留后台

### ISSUE THREAD

**Issue by Suyknow** [mayswind/AriaNg-Native#49]
希望增加一个选项，由用户决定软件叉掉后是否驻留后台。用户界面并不是主程序，我觉得既然没有悬浮窗的话，那么驻留后台（系统托盘）的意义其实不大。随用随开也是ok的。而且涉及驻留后台的问题，我觉得最好还是留一个选项供用户选择。

**Comment by mayswind** [comment]
没有悬浮窗但是有下载完成提醒啊

**Comment by SUCM** [comment]
希望能有這個選項
不然explorer.exe重啟後工作列上的AriaNg圖示就不見了造成無法退出得用TaskManager來強制關閉
關閉aria後工作列上的AriaNg意義也不大

**Comment by mayswind** [comment]
今天发布的1.1.4版本已经增加了这个功能。
