### ISSUE TITLE
Self signed certificates

### ISSUE THREAD

**Issue by outis151** [mayswind/AriaNg-Native#53]
No connection is possible when using self-signed certificates for aria2 rpc

**Comment by mayswind** [comment]
Please go to https://github.com/aria2/aria2/issues

**Comment by outis151** [comment]
I was referring to AriaNG-Native
Whenever i use a self signed certificate for the aria2 rpc, AriaNG doesnt connect and shows only disconnected.

**Comment by jyxjjj** [comment]
> 我指的是 AriaNG-Native 每当我为 aria2 rpc 使用自签名证书时，AriaNG 不连接并且只显示断开连接。

You can just add the root Certificate to your Operating System Key Chain.

Windows:
```
using System.Security.Cryptography.X509Certificates;
                X509Certificate2 certificate = new X509Certificate2(path + "\\root.crt");
                X509Store store = new X509Store(StoreName.Root, StoreLocation.LocalMachine);
                store.Open(OpenFlags.ReadWrite);
                store.Add(certificate);
                store.Close();
```

**Comment by reserveword** [comment]
> You can just add the root Certificate to your Operating System Key Chain.

Adding certificate to OS key chain is insecure and hard to manage. Can we trust a cert by adding it to install directory?

**Comment by jyxjjj** [comment]
> > You can just add the root Certificate to your Operating System Key Chain.
> 
> 
> 
> Adding certificate to OS key chain is insecure and hard to manage. Can we trust a cert by adding it to install directory?


Then ask Aria2 to do that
