### ISSUE TITLE
I can't paste with the right mouse button

### ISSUE THREAD

**Issue by sakuramisaki** [mayswind/AriaNg-Native#55]
OS : Win10 x64
Version:AriaNg Native 1.1.3
我知道你想说Ctrl+V不是更方便吗？
但是我更想要右键粘贴，如下图的chrome。
![Snipaste_2019-09-15_17-12-20.png](https://i.loli.net/2019/09/15/UZatfW3eJ8l9Hn2.png)

**Comment by mayswind** [comment]
能ctrl+v就能右键粘贴啊

**Comment by mayswind** [comment]
哦，你用的AriaNg Native。不支持。
