### ISSUE TITLE
下载多个文件通知太多导致gnome卡死

### ISSUE THREAD

**Issue by zerofancy** [mayswind/AriaNg-Native#56]
前两天想写个爬虫，爬萌娘百科的图片，把url粘贴到AriaNg。

开始时很爽，但下完后我想点开看gnome就假死了(音乐还在放)。

最后发现，是AriaNg native，默认会在单个图片文件下载结束后弹出通知，而我同时下了上千张图片，gnome就扛不住了……(虽然可以禁用通知避免这个问题)

**我觉得，应该设定短时间弹出窗口的阈值或者自己实现一个可以几秒以后自动清除的通知应该更好吧。**

**Comment by mayswind** [comment]
自动清除干嘛还要通知。假死的问题可以去gnome的社区查查。
