### ISSUE TITLE
AriaNG Native客户端不和AriaNG同步更新嘛？对面都已经0.3.0了欸

### ISSUE THREAD

**Issue by Suyknow** [mayswind/AriaNg-Native#6]

**Comment by mayswind** [comment]
AriaNg Native更新会略慢一些，除了要合并AriaNg代码外，其自身也有功能要开发以及要修正相关BUG，目前AriaNg Native还有Bug没修复完，所以发版会晚一段时间。

**Comment by mayswind** [comment]
@Suyknow AriaNg Native 已经同步更新到 v0.4.0 了。

**Comment by Suyknow** [comment]
@mayswind 棒欸！立马更新！
