### ISSUE TITLE
Can't connect to aria2c after SSL cret has been set

### ISSUE THREAD

**Issue by KanJiao** [mayswind/AriaNg-Native#61]
在设置ssl证书之前可以连接aria2，但是上了ssl证书之后就不行了，aria2c运行正常

`
PS C:\Program Files (x128)\Aria2 1.34.0> .\aria2c.exe --conf-path=./aria2.conf

03/02 10:55:19 [WARN] Neither --rpc-secret nor a combination of --rpc-user and --rpc-passwd is set. This is insecure. It is extremely recommended to specify --rpc-secret with the adequate secrecy or now deprecated --rpc-user and --rpc-passwd.

03/02 10:55:19 [NOTICE] RPC transport will be encrypted.

03/02 10:55:19 [NOTICE] IPv4 RPC: listening on TCP port 6800

03/02 10:55:19 [NOTICE] IPv6 RPC: listening on TCP port 6800

03/02 10:56:19 [NOTICE] Serialized session to './aria2.session' successfully.
`

**Comment by mayswind** [comment]
那跟AriaNg Native有什么关系？
