### ISSUE TITLE
选择下载种子部分文件

### ISSUE THREAD

**Issue by ileeoyo** [mayswind/AriaNg-Native#69]
如果选择只下载种子部分文件，看有个issue说是支持，但是没有找到

**Comment by ileeoyo** [comment]
已经找到了，需要先暂停，才能选择下载文件。那么在添加bt任务的时候能否就先选择好文件呢？
另：
![image](https://user-images.githubusercontent.com/24651612/82004745-3c59cb80-9696-11ea-9e04-4d1c43c8368d.png)
这个`（选择文件）`按钮实在不太明显，因为它长的不像是按钮，更像像是文字描述，建议做成按钮形状或者默认展开。导致我看了issue才发现有根据文件类型选择文件，全选，反选等功能

**Comment by mayswind** [comment]
1, 不能。 aria2不提供这个功能。
2, 那个位置很小，做成按钮就太奇怪了。

**Comment by ileeoyo** [comment]
2 那个问题我看了issue，发现还是有不少人都有此疑惑，只是一个建议，或者有其他的一个比较优雅的方式就更好了
