### ISSUE TITLE
Aria2 status disconnected

### ISSUE THREAD

**Issue by baba2580** [mayswind/AriaNg-Native#70]
when i open windows Desktop AriaNg Native is not connecting.

![w](https://user-images.githubusercontent.com/23245020/82212386-194a4880-9930-11ea-9087-965c6fa41681.jpg)

Request for solution

**Comment by rozen30** [comment]
Did you turn on Aria2?

**Comment by NJCCJohnWason** [comment]
Obvioisly your AriaNg **NOT CONNECTED** to Aria2
1.Check your profile of config
2.Check Aria2 is running or not

**Comment by roblogic** [comment]
So this application requires some other process called "aria2" to be installed? This is not written anywhere in the README.

**Comment by mayswind** [comment]
@roblogic 
![image](https://user-images.githubusercontent.com/2211648/98833495-12346b00-2479-11eb-9e5f-80a698b9f2a5.png)
