### ISSUE TITLE
希望可以设置aria2c.exe与程序同步启动

### ISSUE THREAD

**Issue by MoonightsZ** [mayswind/AriaNg-Native#71]
Hope to set aria2c.exe to start synchronously with the program

**Comment by mayswind** [comment]
有很多第三方的软件捆绑了AriaNg和aria2，可以实现你的需求，AriaNg官方文档也推荐了他们 http://ariang.mayswind.net/zh_Hans/3rd-extensions.html。AriaNg Native只做控制台工具，不提供aria2。
