### ISSUE TITLE
关于功能闲聊两句，可否

### ISSUE THREAD

**Issue by underlaw** [mayswind/AriaNg-Native#77]
先感谢作者提供的漂亮UI。
有个功能想说下不知道，作者有没有考虑过
1、就是下载列表文件对应的任务详情，可否弄成点击时，在右边窗口下面，浮动任务详情栏出来。还是对应 总览 区块信息这四栏。
2、下载路径这个好像文件不下载完，是不能点击打开下载目录的。

**Comment by mayswind** [comment]
1、现在在列表页里为了减少网络开销，只取了列表页中显示的信息，其他的都没要求aria2返回，所以如果浮动显示还需要再请求一次，所以如果这样做会有卡顿的感觉，体验不太好
2、这是个bug，新版本已经修复
