### ISSUE TITLE
Retains old config data?

### ISSUE THREAD

**Issue by hl2guide** [mayswind/AriaNg-Native#78]
![1](https://user-images.githubusercontent.com/17044982/91446664-152cb000-e8bb-11ea-9344-39d4d36fc8c1.jpg)

For me it retains the **old setting** from an aria2.conf file:

I have set in the config:

`dir=C:\Downloads`

but GUI loads:

`dir=G:\Downloads`

by default?

**Comment by mayswind** [comment]
do you restart aria2 after you modified config file?

**Comment by hl2guide** [comment]
yes I have.

**Comment by mayswind** [comment]
AriaNg would request aria2 to get all config every time when open the config page.

**Comment by hl2guide** [comment]
yes i'd expect that but I'm having it set it manually each time ☹️
