### ISSUE TITLE
可不可以启动的时候顺便启动aria2c

### ISSUE THREAD

**Issue by lovelyjuice** [mayswind/AriaNg-Native#8]
我的想法是，把aria2c的可执行文件打包到AriaNG.exe的工作目录下，然后运行AriaNG的时候自动启动当前目录下的aria2c.exe，关闭主程序时也同时关闭aria2c
这样我们就可以完全把它当作一个下载器来用了，当然要是能加上右键菜单，如‘在资源管理器中打开’，那就更完美了。

**Comment by mayswind** [comment]
不能，AriaNg Native 的初衷是弥补很多用户没有 Web 服务部署 AriaNg 的问题，而非捆绑 aria2 变成一个所谓的“下载工具”，这不符合 AriaNg 仅提供跨平台下载界面的初衷。
#5

**Comment by lovelyjuice** [comment]
时隔两年，还是希望能有一个工具替代迅雷，看到这里，总有一种99%的遗憾😥

**Comment by mayswind** [comment]
AriaNg及AriaNg Native的初衷从来都不是“代替”现有的现在工具，而是为aria2提供一个更好的前端。同时，现在也有非常多实现你愿望的工具，可以选择他们。

**Comment by AiraNadih** [comment]
如果你想在 Windows 系统上轻松启动 Aria2，可以创建一个名为 `RunAria2.vbs` 的脚本文件，其内容如下：

```vbs
Set objShell = CreateObject("WScript.Shell")
objShell.Run "powershell.exe -Command ""& {aria2c --conf-path='C:\aria2.conf'}""", 0, True
```

在 `aria2c --conf-path='C:\aria2.conf'` 这段代码中，如果你没有将 aria2c 的执行路径添加到系统的 path 环境变量中，请将 `aria2c` 替换为你的 aria2c.exe 文件的完整路径。同理，配置文件路径（即 `C:\aria2.conf`）也应根据你的系统中的实际位置进行相应调整。

修改完成后保存该文件。双击运行此脚本，你应该能在 AriaNg 的界面上看到 `Aria2 状态已连接` 的提示。

**Comment by mayswind** [comment]
> 如果你想在 Windows 系统上轻松启动 Aria2，可以创建一个名为 `RunAria2.vbs` 的脚本文件，其内容如下：
> 
> ```vbnet
> Set objShell = CreateObject("WScript.Shell")
> objShell.Run "powershell.exe -Command ""& {aria2c --conf-path='C:\aria2.conf'}""", 0, True
> ```
> 
> 在 `aria2c --conf-path='C:\aria2.conf'` 这段代码中，如果你没有将 aria2c 的执行路径添加到系统的 path 环境变量中，请将 `aria2c` 替换为你的 aria2c.exe 文件的完整路径。同理，配置文件路径（即 `C:\aria2.conf`）也应根据你的系统中的实际位置进行相应调整。
> 
> 修改完成后保存该文件。双击运行此脚本，你应该能在 AriaNg 的界面上看到 `Aria2 状态已连接` 的提示。
> 
> 我才知道原来有这么个新特性 `启动时执行命令` 了：
> 
> ![image](https://user-images.githubusercontent.com/2211648/226612454-ce3852bb-0632-4259-8b7b-3cf6b448dd26.png)
> 
> 既然已经添加了这样一个特性，是否可以考虑再加入一个 `从磁盘上删除文件` 的新特性呢？我稍微看了下， `task.files` 的 `path` 就是下载任务中文件存储的完整路径。那么，添加一个从磁盘上删除文件的功能，理论上应该并不难实现。
> 
> 不过，与此同时还需要删除相应的 `.aria2` 文件。

“实现”确实很容易，但这个功能事实上是无法实现的，因为AriaNg Native并不负责aria2的配置和启动，无法知道这个aria2实例以及下载路径是否是本地路径。AriaNg Native从来不是一个集成aria2的下载工具，只是为aria2提供前端管理功能。之前AriaNg Native实现了一个类似“打开文件所在目录”的功能，是把这个功能定义为从本机视角找同路径文件打开，也是通过判断路径是否存在的方式是否提供该功能，但删除不同，必须是精确的，所以这个功能无法实现，如果有需求可以使用集成了aria2的真正的下载软件。

**Comment by AiraNadih** [comment]
> 之前受到你的图片的启发，不过后来发现即使在Windows上“启动时执行命令”和“启动时执行命令参数”两个参数的路径都不能用“\”作为路径分隔符，只有将路径分隔符设置成“/”才能正确执行。

不对吧，我这边正常的。我的系统是 Windows 11 23H2 。
