### ISSUE TITLE
"Hide" menu items missing on macOS

### ISSUE THREAD

**Issue by fortinmike** [mayswind/AriaNg-Native#80]
On macOS, the standard "Hide" menu items (and keyboard shortcut) are missing from AriaNg-Native:

<img width="340" alt="Screen Shot 2020-11-15 at 8 57 22 PM" src="https://user-images.githubusercontent.com/118257/99205060-7317b800-2785-11eb-844c-ed4c73a91c17.png">

That seems weird to me as Electron apps have those menu items by default, so it (maybe) means they were manually removed when creating AriaNg-Native.

<img width="428" alt="Screen Shot 2020-11-15 at 8 58 18 PM" src="https://user-images.githubusercontent.com/118257/99205117-8fb3f000-2785-11eb-8c26-297ef8cfd2b2.png">

Would it be possible to bring them back? It's pretty universal on macOS to be able to hide an app using Cmd+H but it doesn't work in AriaNg-Native which makes it kind of a bad citizen on that OS.

**Comment by mayswind** [comment]
"Hide" menu is in dock icon.

**Comment by fortinmike** [comment]
I understand that but this is not a substitute for the menu being in the app's "AriaNg-Native" menu because it prevents the keyboard shortcut from working (and breaks with macOS tradition). If you intend to support macOS well, a menu item should be added, just like in the default Electron app.

**Comment by mayswind** [comment]
I understand, and I would think about whether AriaNg Native should remove support for macos.

**Comment by fortinmike** [comment]
Hum... that's not exactly what I had in mind!!! Please keep support for macOS. Having a suboptimal app is better than having no app at all.

If you do not intend to spend any effort supporting other OSes well, just leave the job to others. I'll try to send you a pull request that adds the menu items on macOS soon, if that's something you'd accept.

**Comment by mayswind** [comment]
I really spend less time in macOS than windows, and I concede AriaNg Native macOS version does not achieve what I think. I really have no time to improve it so I'm always thinking if remove support for macOS sometime.
By the way, I'm very glad to see if someone would commit pull request and improve it.

**Comment by fortinmike** [comment]
The app is perfectly functional on Mac and IMHO it would be a waste to remove Mac support it if it already works. My thinking is Electron makes supporting _all_ OSes pretty easy, especially for apps that are pretty much self-contained (do not access the filesystem, etc.) like AriaNg Native, so the effort to support other platforms is pretty low. There already aren't many GUIs for aria2 on Mac so please keep it around.

The menu thing is only a small gripe. I'll see if I can send you a pull request for it.

**Comment by mayswind** [comment]
the latest version has supported macOS standard menus
