### ISSUE TITLE
文件名,好像会被urlencode了

### ISSUE THREAD

**Issue by lifetin** [mayswind/AriaNg-Native#84]
好用,发现两个问题
1文件名,好像会被urlencode了
2选择框必须点击才会显示,可以一直显示么?

![44](https://user-images.githubusercontent.com/10474968/102716511-4e2fdb00-4317-11eb-90de-700f150cf4ae.png)

**Comment by mayswind** [comment]
1. 这个是aria2下载的meta文件
2. 不能
