### ISSUE TITLE
ed2k://|file不支持吗?

### ISSUE THREAD

**Issue by lifetin** [mayswind/AriaNg-Native#85]
ed2k://|file不支持吗?

**Comment by mayswind** [comment]
aria2不支持

**Comment by lifetin** [comment]
怎么才能支持呀?
然后你们这体验这块不能优化么?
比喻保存文件的路径, 没有选择,只能完整输入
修改了配置, 提示要重启, 暂时不想重新,这个提示框 不能关闭,

**Comment by mayswind** [comment]
1、aria2不支持ed2k，有问题找 http://github.com/aria2/aria2
2、aria2不支持，AriaNg Native啥也做不了
3、AriaNg和AriaNg Native会保存最近使用过的路径，点击有下拉框
4、AriaNg Native没有要重启的提示框不能关闭
