### ISSUE TITLE
macOS arm64版本提示已损坏,x64版本可正常使用

### ISSUE THREAD

**Issue by jigaowan** [mayswind/AriaNg-Native#90]
“AriaNg Native.app”已损坏，无法打开。 您应该将它移到废纸篓。

**Comment by mayswind** [comment]
你是m1的mac么？

**Comment by jigaowan** [comment]
嗯，macbookair m1

**Comment by mayswind** [comment]
我手头没有m1的设备，那我就先从release里把arm64的下载删掉吧

**Comment by jigaowan** [comment]
最近遇到其他应用有类似问题，可以通过`sudo xattr -cr your.app`来解决，能否把arm版本放出来再试一下

**Comment by n0thing2speak** [comment]
> 我手头没有m1的设备，那我就先从release里把arm64的下载删掉吧

这不是包的问题啊，放出来吧老哥

**Comment by billzhong** [comment]
请问 Apple Silicon 的版本预计什么时候会再有呢？

**Comment by mayswind** [comment]
@billzhong 没有官方发布计划了，可以自行编译

**Comment by ITJesse** [comment]
我这边使用 23.2.0 版本的 electron-builder 打包成功，并且可以正常运行。
我看 package.json 中也有配置打包 arm64 版本。
请问可否将其释出？
