### ISSUE TITLE
download stops and won't resume

### ISSUE THREAD

**Issue by aliafshany** [mayswind/AriaNg-Native#97]
hello there
this is a little bit strange but when I uninstall the app, and then reinstall it and enter this URL for example.

[http://megaandroid.ir:6969/dl_x/d2779326-dcc5-4f3b-a47c-a303164e2e40](url)

it works and downloads but then I try to add other links like 
[http://megaandroid.ir:8080/dl_x/bbe70673-bc6f-4472-9d17-ab8ee8088573](url)

which results in failure and I can not download it.

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/40741745/180759764-8654dff6-9e81-4f36-8742-4082d6d3c433.png">

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/40741745/180764203-94cf1024-2057-480e-97bc-ddb6b82487b0.png">
but it does support resume

**Comment by mayswind** [comment]
You should go to [http://github.com/aria2/aria2/issues](http://github.com/aria2/aria2/issues) for help.
