### ISSUE TITLE
Show bottom bar on shorter height windows

### ISSUE THREAD

**Issue by hl2guide** [mayswind/AriaNg-Native#98]
Please show the bottom bar when the window is set to a shorter height.

(I tested on a 1920x1080 screen with the window height set to 50% of screen's height)

![a](https://user-images.githubusercontent.com/17044982/193407266-58323848-2905-4a21-84c7-959693c8fb0c.jpg)

**Comment by mayswind** [comment]
![image](https://user-images.githubusercontent.com/2211648/193410914-67dddf39-124e-41ff-9c4c-de62db53170d.png)

The min width and height of AriaNg Native window is 800 and 400. The bottom bar should be always shown in the window. Could you give more information about your question.

**Comment by hl2guide** [comment]
Example of issue:
![example](https://user-images.githubusercontent.com/17044982/193589746-87d276ba-8bde-49a4-a89a-c09dbe002ac2.jpg)

**Comment by hl2guide** [comment]
@mayswind after more testing it seems to happen because I'm using [Microsoft PowerToys](https://learn.microsoft.com/en-us/windows/powertoys/).
