### ISSUE TITLE
感谢开发者开发

### ISSUE THREAD

**Issue by RyensX** [mayswind/AriaNg-Native#99]
试用了一下，感觉各方面都不错。
但有两点我觉得还可以再做一下提升体验：
1. Native虽然支持多个RPC方案，但是每次还是得手动自己启动aria2，如果可以做成打开程序(Native Only)后没有连接上则根据方案配置的aria2路径启动aria2那就更加方便了
2. 删除任务希望可以可选把文件也删除了，不然明明在下载器删除了任务还得手动去资源管理器找到手动删除太麻烦了

**Comment by mayswind** [comment]
1. 与 #8 重复
2. 与 mayswind/AriaNg#11 重复

提问前请搜索已有issues

**Comment by RyensX** [comment]
好的，谢谢
